config/routes.rb
Rails.application.routes.draw do
  get 'photos/index'
  devise_for :users
  get 'home/index'
  get 'home/show'
  root "home#index"
  resources :albums do
    collection do
      delete "purge"
    end
  end

  delete "images/:id/purge", to: "albums#purge", as: "purge_image"
  resources :home


end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :description, :presence =>true;
  validates :title, :description, :length =>{:minimum => 3}
  validates :cover_image, :presence => true

  has_one_attached :cover_image
  has_many_attached :images, :dependent => :destroy


  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings


  def self.tagged_with(name)
    Tag.find_by_name!(name: name).albums
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end

  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @albums = current_user.albums
    @q = @albums.ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    # @album = Album.new
    @album = current_user.albums.build
  end

  def create
    # @album = current_user.albums.new(album_params)
    @album = current_user.albums.build(album_params)

    if @album.save
      redirect_to @album, notice: "Album created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album, notice: "Album Updated Succesfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path, status: :see_other
  end
  
  

  def correct_user
    @album = current_user.albums.find_by(id: params[:id])
    redirect_to root_path, alert: "You are not authorized" if @album.nil?
  end


  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end


  def purge
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge
    redirect_to  albums_url, notice: "Image deleted"
  end



  private
    def album_params
      params.require(:album).permit(:title, :description, :all_tags, :published, :cover_image, :images => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :password_confirmation, :dob, :gender])  
  end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to albums_path
    else
    @albums = Album.where(published: true)
    end
    

       
    if params[:tag]
      @albums = Album.tagged_with(params[:tag])
    else
      @albums = Album.where(published: true)
    end


    @q = Album.where(published: true).ransack(params[:q])
    @albums = @q.result.includes(:tags)
  end

  def show
    @album = Album.find(params[:id])
  end

  

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_add_photos.html.erb
<div class="my-5">
        <%= form_with model: album do |form| %>

    

        <div class="field">
          <%= form.file_field :images, :multiple =>true, class: "form-control w-50" %>
        </div>
        <br />


        <div>
          <%= form.submit "Add Images", class: "btn btn-secondary" %>
        </div>
        <% end %>

</div>

app/views/albums/_footer.html.erb
<footer class="footer-basic">
  <div class="social">
    <a href="https://www.instagram.com/" target="_blank"><i class="bi bi-instagram"></i></a>
    <a href="https://www.google.com" target="_blank"><i class="bi bi-google"></i></a>
    <a href="https://twitter.com/" target="_blank"><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/" target="_blank"><i class="bi bi-github"></i></a>            
    <hr>
    <p class="copyright">Malik Arbaz © 2022</p>
  </div>
  </footer>

app/views/albums/_form.html.erb
<div class="bg-light p-5">
        <%= form_with model: album do |form| %>

        <div class="field form-group">
          <%= form.label :title , class:'form-label fw-bold'%>
          <%= form.text_field :title, required: true, class: "form-control", placeholder: "Title" %>
          <% album.errors.full_messages_for(:title).each do |message| %>
          <p><%= message %></p>
          <% end %>
        </div>
        <br />
        <div class="field form-group">
          <%= form.label :description, class:'form-label fw-bold' %>
          <%= form.text_area :description, required: true, class: "form-control", placeholder: "Description" %>
          <% album.errors.full_messages_for(:description).each do |message| %>
           <p><%= message %></p>
          <% end %>
        </div>
        <br />
         <div class="field">
          <%= form.label :Tags, class:'form-label fw-bold' %>
          <%= form.text_field :all_tags, class: "form-control" %>
        </div>
        <br>
        

        <div class="field">
          <%= form.label :cover_image, class:'form-label fw-bold' %>
          <%= form.file_field :cover_image, class: "form-control" %>
          <% album.errors.full_messages_for(:cover_image).each do |message| %>
          <p><%= message %></p>
          <% end %>
        </div>
        
        
        <br />

        <div class="field">
          <%= form.label :Images, class:'form-label fw-bold' %>
          <%= form.file_field :images, :multiple =>true, class: "form-control" %>
        </div>
        <br />

        <div class="field">
         <%= form.label :publish, class:'form-label fw-bold' %> 
         <%= form.check_box :published %>
        </div>
        <br />

        <div>
          <%= form.submit %>
        </div>
        <% end %>

</div>

app/views/albums/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <i class="bi bi-camera-fill"></i>
      Gallery
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%= link_to  root_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do %>
          Home
        <% end %>
        <%= link_to new_album_path, class: "nav-link #{'active fw-bold' if current_page?(new_album_path)}" do %>
          New Album
        <% end %>
        
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if current_user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <div class="fa fa-user"></div>
              <b><%= current_user.email %></b>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                <div class="fa fa-cog"></div>
                <b>Account settings</b>
              <% end %>
              <%= link_to destroy_user_session_path, class: "dropdown-item" do %>
                <div class="fa fa-sign-out-alt"></div>
                <b>Sign out</b>
              <% end %>
            </ul>
          </li>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "nav-link btn btn-warning me-2" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn btn-primary" %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/albums/_published_album.html.erb
<h1 class="text-center mt-5 mb-2">All Published Albums</h1>
<hr>

<div class="search mt-4 d-flex justify-content-end">
  <%= search_form_for @q, url: all_albums_path do |f|%>
  <%= f.search_field :tags_name_eq , placeholder: "Search By Tag", class:"rounded"%>
  <%= f.submit "Search", class:"rounded" %>
<% end %>
</div>
<div class="row mt-5">
  <% @albums.each do |album| %>
    <div class = "col-lg-4 text-center">
      <div class="card m-3">
      <% if album.cover_image.attached? %>
        <div class="card-header">
          <%=link_to home_path(id: album.id) do%>
            <%= image_tag(album.cover_image, class: "img-fluid img mb-2") %><br>
          <%end%>
        </div>
      <%end%>
        <div class="card-body">
          <%=link_to home_path(id: album.id), class:"text-decoration-none text-black" do%>
            <h5 class="card-title">
              <strong>Title:</strong> 
              <%= album.title %>
            </h5>
          <%end%>
          <h5 class="card-title">
          <strong>Tag: </strong>  
          <small class="text-muted"><%= album.all_tags %></small>
          </h5>
          <p > 
          <strong>Created at: </strong>
          <span class="text-muted"><%= album.created_at%></span>
          </p>
          <p > 
          <strong>Updated at: </strong>
          <span class="text-muted"><%= album.updated_at%></span>
          </p>
          <p > 
          <strong>Total Images: </strong>
          <span class="text-muted"><%= album.images.count%></span>
          </p>
        </div>
        <div class="card-footer text-muted">
          <%= link_to "Edit", edit_album_path(album), class: "btn btn-success"%>
          <%= link_to "Delete", album_path(album), data: {turbo_method: :delete, turbo_confirm: "Are you sure"}, class: "btn btn-success"%>
        </div>
  
      </div>
      <br>
    </div>
  <% end %>
</div>
<br>

app/views/albums/about_us.html.erb
<h1>About Us</h1>
<p>Pexels provides high quality and completely free stock photos licensed under the Pexels license. 
All photos are nicely tagged, searchable and also easy to discover through our discover pages.
<p>

app/views/albums/edit.html.erb
<h1> Edit Your album </h1><br>
<%= render 'form', album:@album %>

app/views/albums/index.html.erb
<h1 class="text-center mt-5 mb-2">My Albums</h1>
<hr>

<div class="search mt-4 d-flex justify-content-end">
  <%= search_form_for @q do |f|%>
    <%= f.search_field :tags_name_eq , placeholder: "Search By Tag", class:"rounded" %>
   <%= f.submit "Search", class:"rounded"%> 
  <% end %>
</div>



<div class="row mt-5">
  
  <% @albums.each do |album| %>
    <div class = "col-lg-4 text-center">
      <div class="card m-3 cardDesign">
      <%=link_to album, class:"text-decoration-none text-black" do%>
            <h3 class="card-title">
              <strong>Album:</strong>
              <%= album.title %>
            </h3>
      <% end %>
      <% if album.cover_image.attached? %>
        <div class="card-header">
          <%=link_to album do%>
            <%= image_tag(album.cover_image, class: "img-fluid img mb-2") %><br>
          <%end%>
        </div>
      <%end%>
        <div class="card-body">
          <h5 class="card-title">
          <strong>Tag: </strong>  
          <small class="text-muted"><%= album.all_tags %></small>
          </h5>
          <p > 
          <strong>Created at: </strong>
          <span class="text-muted"><%= album.created_at%></span>
          </p>
          <p > 
          <strong>Updated at: </strong>
          <span class="text-muted"><%= album.updated_at%></span>
          </p>
          <p > 
          <strong>Total Images: </strong>
          <span class="text-muted"><%= album.images.count%></span>
          </p>

        </div>
        <div class="card-footer text-muted">

          <%= link_to 'Edit', edit_album_path(album), class: "btn btn-secondary" %>
        <%= link_to "Delete", album_path(album), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger" %>
        </div>
      </div>  
    </div>
  <% end %>
</div>

<br>

app/views/albums/new.html.erb
<h1 class="text-center my-4">New Album</h1>
<hr>
 <%= render 'form', album:@album%>



<br>

app/views/albums/show.html.erb
<h1 class="my-3">Description:</h1>
<p class="lead my-2"><%= @album.description %></p>
<div class="row mt-5">
  <% @album.images.each do |image|%>
    <div class="col-lg-4 my-2">
      <div class="card ">
        <%=link_to image, target: "_blank" do%>
        	<%= image_tag(image,class:'img-fluid img') %>
        <%end%>
        <div class="card-footer"> 
            <%= link_to 'View', image, target: "_blank", class: "btn btn-secondary" %>
            <%= link_to "Delete", purge_albums_path(id: image.id), data: {turbo_method: :delete, turbo_confirm: "Are youu sure?"}, class:"btn btn-danger"%>
        </div>
        
      </div>
  	</div>
  <% end %>

</div>



<br>


<!-- Button trigger modal -->
<button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Add Images
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model: @album do |form| %>
        <div class="field">
          <%= form.file_field :images, :multiple =>true, class: "form-control w-50" %>
        </div>
        <br />
        <div>
          <%= form.submit "Add Images", class: "btn btn-secondary" %>
        </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="text-center mt-5 mb-2">All Published Albums</h1>
<hr>

<div class="search mt-4 d-flex justify-content-end">
  <%= search_form_for @q, url: root_path do |f|%>
  <%= f.search_field :tags_name_eq , placeholder: "Search By Tag", class:"rounded"%>
  <%= f.submit "Search", class:"rounded" %>
<% end %>
</div>
<div class="row mt-5">
  <% @albums.each do |album| %>
    <div class = "col-lg-4 text-center">
      <div class="card m-3 cardDesign">
        <%=link_to home_path(id: album.id), class:"text-decoration-none text-black" do%>
            <h3 class="card-title">
              <strong>Album:</strong> 
              <%= album.title %>
            </h3>
          <%end%>
      <% if album.cover_image.attached? %>
        <div class="card-header">
          <%=link_to home_path(id: album.id) do%>
            <%= image_tag(album.cover_image, class: "img-fluid img mb-2") %><br>
          <%end%>
        </div>
      <%end%>
        <div class="card-body">
          <h5 class="card-title">
          <strong>Tag: </strong>  
          <small class="text-muted"><%= album.all_tags %></small>
          </h5>
          <p > 
          <strong>Created at: </strong>
          <span class="text-muted"><%= album.created_at%></span>
          </p>
          <p > 
          <strong>Updated at: </strong>
          <span class="text-muted"><%= album.updated_at%></span>
          </p>
          <p > 
          <strong>Total Images: </strong>
          <span class="text-muted"><%= album.images.count%></span>
          </p>
        </div>
  
      </div>
      <br>
    </div>
  <% end %>
</div>
<br>

app/views/home/show.html.erb
<h1 class="my-3">Description:</h1>
<p class="lead my-2"><%= @album.description %></p>
<div class="row mt-5">
    <% @album.images.each do |image|%>
    <div class="col-lg-4 my-3">
        <div class="card">
        <%=link_to image, target: "_blank" do%>
            <%= image_tag(image,class:'img-fluid img')%>
        <%end%>
        <div class="card-footer"> 
            <%= link_to 'View', image, target: "_blank", class: "btn btn-secondary mt-2" %>
        </div>
        </div>
    </div>
    <% end %>
</div>


<br>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%# bootstrap Icon CDN %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">

    <title>Gallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path('android.png') %>
  </head>
  <body class="bg-img">
    <%= render 'albums/header' %>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-warning" role="alert">
          <%= flash[:notice] %>
          <button type="button" class="float-end" data-bs-dismiss="alert" aria-label="Close">&times;</button>
        </div>

      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="float-end" data-bs-dismiss="alert" aria-label="Close">&times;</button>
        </div>

      <% elsif flash[:alert] %>
        <div class="alert" role="alert">
          <%= flash[:alert] %>
          <button type="button" class="float-end" data-bs-dismiss="alert" aria-label="Close">&times;</button>
        </div>
      <% end %>



      <%= yield %>
    </div>
    <%= render 'albums/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>

app/views/photos/index.html.erb
<h1>Photos#index</h1>
<p>Find me in app/views/photos/index.html.erb</p>